---
version: '2'
services:
  vault:
    image: vault:1.3.0
    ports:
      - "8200:8200"
    command: vault server -dev -config="/vault/vault.hcl" -log-level="debug"
    volumes:
      - ./docker:/vault
    links:
      - kafka:kafka
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: "root"
      VAULT_DEV_LISTEN_ADDRESS: "0.0.0.0:8200"

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    extra_hosts:
      - "moby:127.0.0.1"

  kafka:
    image: confluentinc/cp-kafka:5.0.1
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

      KAFKA_SSL_KEYSTORE_FILENAME: kafka.broker0.keystore.jks
      KAFKA_SSL_TRUSTSTORE_FILENAME: kafka.broker0.truststore.jks

      KAFKA_SSL_KEY_CREDENTIALS: broker0_sslkey_creds

      KAFKA_SSL_KEYSTORE_CREDENTIALS: broker0_keystore_creds
      KAFKA_SSL_TRUSTSTORE_CREDENTIALS: broker0_truststore_creds

      KAFKA_SECURITY_INTER_BROKER_PROTOCOL: SSL
      KAFKA_SSL_CLIENT_AUTH: required
      KAFKA_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM: ""
      KAFKA_LISTENER_NAME_INTERNAL_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM: 
      KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: "true"
      KAFKA_AUTHORIZER_CLASS_NAME: kafka.security.auth.SimpleAclAuthorizer
      # TODO: change this
      KAFKA_ADVERTISED_LISTENERS: SSL://kafka:9092
    volumes:
      - ./tmp/secrets:/etc/kafka/secrets
    extra_hosts:
      - "moby:127.0.0.1"
